### ISSUE TITLE
Dylan's mini-code TO-DO - Alpha version 1.0.0

### ISSUE THREAD

**Issue by DylanMeeble** [DylanMeeble/ProjectNinja_Code#8]
- [ ] No running inside.

- [ ] Climbing (adjust speed and add animation)

- [ ] Get a decent grasp of cutscenes (for Schoolbus leaving and Damien in Forest)

- [ ] Add "Zoom" and "Cinematic Border" for cutscenes.

- [ ] Confirm "Z-depth" works and try to add opacity function when behind other objects. #3
