### ISSUE TITLE
Background, Objects, Animations TO-DO - Alpha version 1.0.0

### ISSUE THREAD

**Issue by DylanMeeble** [DylanMeeble/ProjectNinja_Code#9]
- [ ] Finish (Modern) Town for Opening Gameplay

- [ ] (Modern) Forest

- [ ] Brato's Animations ( #7 )

- [ ] Damien

- [ ] Mom and Dad

- [ ] Other Interact-able NPC's available in opening gameplay

- [ ] Cutscene sprites for opening.
